### ISSUE TITLE
Update boto3 dependency

### ISSUE THREAD

**Issue by nkallergis** [nautobot/nautobot-app-secrets-providers#145]
### Environment
* Python version:  N/A
* Nautobot version:  >2.2
* nautobot-secrets-providers version:  3.1.0

### Expected Behavior
I'm able to install Secrets Providers plugin alongside newer versions of boto3/jmespath.

### Observed Behavior
Cannot install boto3 versions later than 1.19.

### Steps to Reproduce
1. Install Secrets Providers plugin version 3.1.0
2. Install Device Onboarding plugin version 4 (depends on jdiff ^0.0.6 which depends on jmespath >1.0.0)
3. Dependency resolution fails as Secrets Providers pins boto3 version to <1.20

Updating boto3 dependency to >=1.34 in order to resolve (among others) [Device Onboarding issue 217](https://github.com/nautobot/nautobot-app-device-onboarding/issues/217).

**Comment by gertzakis** [comment]
Any luck for 1.6 ltm also?
