### ISSUE TITLE
Add Azure Keyvault as Supported Secret Backend

### ISSUE THREAD

**Issue by kingfetty** [nautobot/nautobot-app-secrets-providers#20]
### Environment
* Nautobot version:  1.2.4
* secrets version:  1.0.1

  

### Proposed Functionality
Add Azure Keyvault as a supported secrets backend.

### Use Case
We have multiple network environments that utilize various Azure Keyvaults as secret storage for access credentials to network devices, ssl private keys, etc.  The goal would be to use nautobot secret storage feature to store the secrets within the same keyvault environment.  We deal with many enterprises that do not have AWS presence, but prefer Azure.

**Comment by jathanism** [comment]
Thanks for the submission! 

If you wouldn't mind providing some more background details on the most common types of secrets you would need? This appears to be a robust solution and we likely wouldn't be able to implement full support for everything out the gate.

The big starting points from my perspective would be:
- Object type: [Secrets](https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates)?
- Authentication method

Any background you can share will help us to scope and prioritize implementing this in the future! Thanks in advance!

**Comment by kingfetty** [comment]
Azure Key Vault supports storing 3 types of data, Certificates, Keys, and Secrets. Of the 3, only secret storage supports accessing the secret value in a way that is useful.  For this reason all use cases would be to access secret storage.  Secrets must be stored using a name following DNS host naming rules [a-zA-Z0-9\-]

As for authentication, AKV has it's own permissions system and only supports OAUTH2 methods for authentication.  Users of the setup would need to create a service principal within Azure to represent the Nautobot service and grant the appropriate permissions to this principal. Microsoft provides python libraries for both the authentication (Azure Identity Module) and the keyvault access

Below are example link to using the python libraries:

https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals
https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python

**Comment by jathanism** [comment]
> Azure Key Vault supports storing 3 types of data, Certificates, Keys, and Secrets. Of the 3, only secret storage supports accessing the secret value in a way that is useful. For this reason all use cases would be to access secret storage. Secrets must be stored using a name following DNS host naming rules [a-zA-Z0-9-]
> 
> As for authentication, AKV has it's own permissions system and only supports OAUTH2 methods for authentication. Users of the setup would need to create a service principal within Azure to represent the Nautobot service and grant the appropriate permissions to this principal. Microsoft provides python libraries for both the authentication (Azure Identity Module) and the keyvault access
> 
> Below are example link to using the python libraries:
> 
> https://docs.microsoft.com/en-us/azure/developer/python/azure-sdk-authenticate-service-principals https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python
> 
> Creating service principal for keyvault access of application https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

THANK YOU for this background. This helps a lot!

**Comment by JonathanNathanson** [comment]
This would be a fantastic addition - I would be happy to help test as and when.
