### ISSUE TITLE
Plugin `home_view_name` view is out of date

### ISSUE THREAD

**Issue by nniehoff** [nautobot/nautobot-app-secrets-providers#52]
### Environment
* Python version:  3.10
* Nautobot version:  1.4.5
* secrets version:  1.3.0

### Expected Behavior

When visiting the page `/plugins/secrets/` which is the plugin's `home_view_name` the page should be up to date.

### Observed Behavior

The view is outdated based on the README in this repo.

### Steps to Reproduce
1.  Go to `/plugin/secrets/`

3.

**Comment by DistantVoyager** [comment]
https://demo.nautobot.com/plugins/secrets/
![image](https://github.com/nautobot/nautobot-app-secrets-providers/assets/111259311/30aadcef-bf9a-473d-9cb0-afdd0cafe165)

https://demo.nautobot.com/apps/installed-apps/nautobot_secrets_providers/
![image](https://github.com/nautobot/nautobot-app-secrets-providers/assets/111259311/6e6455b8-ea84-4daf-9ecf-1a79d40299cd)

1st Screenshot: update URL to be `/plugins/secrets-providers/`
2nd Screenshot: change `Secrets Management Extensions` references to `Secrets Providers`

**Comment by DistantVoyager** [comment]
Looks to be fixed in newer versions
